use color_eyre::{eyre::WrapErr, Result};
use std::fs;
use std::path::Path;

pub fn run(policy: Option<&str>, output: Option<&str>, binary: Option<&str>) -> Result<()> {
    let policy_path = policy.unwrap_or("policy.json");
    let binary_path = binary.unwrap_or("/bin/sh");

    if !Path::new(policy_path).exists() {
        color_eyre::bail!("Policy file not found: {}", policy_path);
    }

    let policy_content = fs::read_to_string(policy_path).context("Failed to read policy file")?;

    println!("Creating bubblewrap wrapper for: {}", binary_path);

    let script = generate_wrapper(&policy_content, binary_path);

    if let Some(out_path) = output {
        fs::write(out_path, &script)?;
        println!("Wrapper written to: {}", out_path);
    } else {
        println!("{}", script);
    }

    Ok(())
}

fn generate_wrapper(policy: &str, binary: &str) -> String {
    format!(
        r#"#!/bin/bash
# Bubblewrap sandbox wrapper generated by myjail
# Policy: {}

exec bwrap \
    --ro-bind /usr /usr \
    --ro-bind /bin /bin \
    --ro-bind /lib /lib \
    --ro-bind /lib64 /lib64 \
    --proc /proc \
    --dev /dev \
    --tmpfs /run \
    --tmpfs /tmp \
    -i \
    --chdir / \
    {} "$@"
"#,
        policy, binary
    )
}
