#!/bin/bash
# Bubblewrap sandbox wrapper generated by bubblepolicy
# Binary: {binary}
# Policy entries: {entries}

set -e

# Check if bwrap is available
if ! command -v bwrap &> /dev/null; then
    echo "Error: bubblewrap (bwrap) is not installed"
    exit 1
fi

# Create the sandbox with unshare-all
exec bwrap \
    --unshare-all \
{args_str} \
    --proc /proc \
    --dev /dev \
    --tmpfs /run \
    --tmpfs /tmp \
    -- \
    {binary} "$@"
